version: "3.5"
services:
  mongo:
    container_name: mongo
    image: mongo:3.4
    command: --nojournal
    networks:
      - fiware
#    ports:
#      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  orion:
    container_name: orion
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -dbuser root -dbpwd example #-logLevel DEBUG
    networks:
      - fiware
  web:
    container_name: web
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - orion
    networks:
      - fiware
    command: bash -c "sleep 10 && sh /entities/createPredictionEntities.sh && sh /entities/subscribeReqPredictionTicket.sh && sh /entities/subscribeResPredictionTicket.sh && npm start"
    environment:
      - URL_CB=http://orion:1026/v2/entities/ReqTicketPrediction1/attrs
      - MONGO_URI=mongodb://root:example@mongo:27017/sth_test?authSource=admin
    volumes:
      - ./entities:/entities
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "9001:9001"
      - "4040:4040"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    networks:
         - fiware
    command: bash -c "sleep 20 && sh /prediction-job/spark-jobs/run-spark-jobs-predict.sh"
    volumes:
      - ./prediction-job:/prediction-job
networks:
  fiware:
