version: "3.5"
services:
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "9001:9001"
      - "4040:4040"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    networks:
         - ckan_yoda
    command: bash -c "sleep 20 && sh /prediction-job/spark-jobs/run-spark-jobs-predict.sh"
    volumes:
      - ./prediction-job:/prediction-job
    logging:
      options:
        max-size: 50m
networks:
  ckan_yoda:
    external: true
    name: ckan_yoda
